Storing order details in db, basic ui styling for web flow pages
Basic styling for cancel, previous, next, finish buttons
Include buttons in a div with padding-right:200px;
Include class btn, btn-danger

display images of selected products in
selected products page
Final order details confirmation page
adjust height and width of the image
display product details along with the image in a table

List used instead of table in products page

Displaying products by category implemented.
Category can be selected from the categories dropdown menu. On clicking
a particular category the list of products
that belong to that category is displayed.

Image carousal (unwanted items/images removed)

Unwanted code related to search and angular js removed in products.jsp
Footer is displayed properly after removing the unwanted code.

Many-to-Many mapping between order and product created.
Name of the Order table has been changed to Order2 as the table with
table name "Order" is not getting created.

The following exception is thrown when trying to add multiple products.
org.springframework.dao.DuplicateKeyException: A different object with
the same identifier value was already associated
with the session : [com.niit.shoppingcart.model.Product#17]; nested
exception is org.hibernate.NonUniqueObjectException:
A different object with the same identifier value was already associated
with the session :
[com.niit.shoppingcart.model.Product#17]